version: '3'
services:
  mysql:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3308:3306
#  student:
#    image: student:1.0
#    environment:
#      DB_CONNECTION_ADDR: mysql
#    ports:
#      - 9090:9090
#    depends_on:
#      - mysql
volumes:
  db_data:
